# configs/config_niaf_vel.yaml
# NIAF+速度监督模型训练配置

defaults:
  - _base
  - action_stats: pick_pineapple
  - callbacks: default
  - datamodule: default_vel
  - model: niaf_vel
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

ckpt_monitor: train/total_loss_epoch

root_data_dir: /data1/lhy/traindata/pick_pineapple
lang_text: "Pick up the pineapple toy and put it on the plate"
action_mode: delta_first
action_min: ${action_min_delta_first}
action_max: ${action_max_delta_first}

fps: 30
act_loss_weight: 1.0
vel_loss_weight: 0.1
jerk_loss_weight: 0.0

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: .
  group: niaf_vel
  log_model: false
  project: niaf
  name: seq${chunk_size}_${now:%Y%m%d_%H%M%S}
